{
 "title": "Messwerte im Detail",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "Messstelle",
    "query": {
     "query": "SELECT device_id FROM clients WHERE FIND_IN_SET('${__user.login}', grafana_ids) ORDER BY id;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Zählerstand",
   "type": "stat",
   "description": "zum Ende des gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (timestamp_client) AS \"time_sec\",\n  MAX(meter_value)/10 AS \"Meter Value\"\nFROM sml_v1\nWHERE\n  id = \"$id\"\n  AND\n  $__unixEpochFilter(timestamp_client)\n"
    }
   ]
  },
  {
   "title": "Leistung, CO2-Emission und Börsenstrompreis",
   "type": "timeseries",
   "description": "Day-Ahead Börsenpreis [Quelle: energy-charts.info]\nCO2-Emissionswerte [Quelle: GreenGridCompass] mit ca. 6h Verzug",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp_client as 'time', \n  (meter_value - LAG(meter_value) OVER (PARTITION BY id ORDER BY timestamp_client)) *360 / NULLIF(timestamp_client - LAG(timestamp_client) \n  OVER (PARTITION BY id ORDER BY timestamp_client), 0) AS \"Leistung\" \nFROM sml_v1 \nWHERE\n  id = \"$id\"  \n  AND\n  $__unixEpochFilter(timestamp_client)\nORDER BY from_unixtime(timestamp_client)\n"
    },
    {
     "dataset": "hz-v1",
     "rawSql": "SELECT \r\n  ts_utc as time, \r\n  value as \"CO2 g/kWh\"\r\nFROM `hz-v1`.co2_intensity_hourly \r\nWHERE \r\n  zone = \"DE_LU\" \r\n  AND $__timeFilter(ts_utc)"
    },
    {
     "dataset": "hz-v1",
     "rawSql": "SELECT\r\n  (unix_timestamp) AS \"time_sec\",\r\n  price_eur_mwh/10 as \"Börsenstrompreis [ct/kWh]\"\r\nFROM power_prices\r\nWHERE\r\n  unix_timestamp between $__unixEpochFrom() AND $__unixEpochTo()\r\n  ORDER by unix_timestamp ASC"
    }
   ]
  },
  {
   "title": "Letzte gemessene Leistung",
   "type": "stat",
   "description": "im gewählten Zeitraum",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hz_v1",
     "rawSql": "SELECT \r\n  timestamp_client as 'time', \r\n  (meter_value - LAG(meter_value) OVER (PARTITION BY id ORDER BY timestamp_client)) *360 / NULLIF(timestamp_client - LAG(timestamp_client) \r\n  OVER (PARTITION BY id ORDER BY timestamp_client), 0) AS \"Grid\" \r\nFROM sml_v1 \r\nWHERE\r\n  id = \"$id\"  \r\n  AND\r\n  $__unixEpochFilter(timestamp_client)\r\nORDER BY from_unixtime(timestamp_client) DESC\r\nLimit 1\r\n"
    }
   ]
  },
  {
   "title": "Berechnete Jahresenergie",
   "type": "stat",
   "description": "Wäre das ganze Jahr wie so wie der ausgewählte Zeitraum, wäre dies der Jahresverbrauch",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\n\n  (\n    (\n      (3600 / 10 * (\n        (SELECT meter_value FROM sml_v1 WHERE id = \"$id\" AND timestamp_client <= $__unixEpochTo() ORDER BY timestamp_client DESC LIMIT 1) - \n        (SELECT meter_value FROM sml_v1 WHERE id = \"$id\" AND timestamp_client >= $__unixEpochFrom() ORDER BY timestamp_client ASC LIMIT 1)\n      )) \n      / \n      (\n        (SELECT timestamp_client FROM sml_v1 WHERE id = \"$id\" AND timestamp_client <= $__unixEpochTo() ORDER BY timestamp_client DESC LIMIT 1) - \n        (SELECT timestamp_client FROM sml_v1 WHERE id = \"$id\" AND timestamp_client >= $__unixEpochFrom() ORDER BY timestamp_client ASC LIMIT 1)\n      )\n    ) * 8760\n  ) AS Jahresenergie_kWh\n"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hz-v1",
     "rawSql": "WITH verbrauch AS (\r\n  SELECT\r\n    timestamp_client AS ts,\r\n    meter_value / 10 AS wh,\r\n    LAG(meter_value / 10) OVER (ORDER BY timestamp_client) AS wh_prev,\r\n    LAG(timestamp_client)  OVER (ORDER BY timestamp_client) AS ts_prev\r\n  FROM sml_v1\r\n  WHERE id = \"$id\"\r\n    AND timestamp_client BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\r\n),\r\ndeltas AS (\r\n  SELECT\r\n    ts,\r\n    (wh - wh_prev) AS delta_wh\r\n  FROM verbrauch\r\n  WHERE wh_prev IS NOT NULL\r\n    AND (wh - wh_prev) >= 0\r\n),\r\ngesamt_kwh AS (\r\n  SELECT SUM(delta_wh) / 1000 AS total_kwh FROM deltas\r\n),\r\nco2_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    c.value\r\n  ) AS co2_gramm\r\n  FROM deltas d\r\n  JOIN co2_intensity_hourly c\r\n    ON c.zone = 'DE_LU'\r\n    AND c.emission_type = 'Operational'\r\n    AND c.forecast_type = 'Actual'\r\n    AND c.ts_utc = DATE_FORMAT(FROM_UNIXTIME(d.ts), '%Y-%m-%d %H:00:00')\r\n),\r\npreis_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    (p.price_eur_mwh / 1000)\r\n  ) AS kosten_eur\r\n  FROM deltas d\r\n  JOIN power_prices p\r\n    ON p.bidding_zone = 'DE-LU'\r\n    AND p.unix_timestamp = (\r\n      FLOOR(d.ts / 900) * 900\r\n    )\r\n)\r\nSELECT\r\n  gesamt_kwh.total_kwh                                        AS \"Verbrauch (kWh)\"\r\nFROM gesamt_kwh, co2_weighted, preis_weighted;"
    }
   ]
  },
  {
   "title": "CO2 gesamt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hz-v1",
     "rawSql": "WITH verbrauch AS (\r\n  SELECT\r\n    timestamp_client AS ts,\r\n    meter_value / 10 AS wh,\r\n    LAG(meter_value / 10) OVER (ORDER BY timestamp_client) AS wh_prev,\r\n    LAG(timestamp_client)  OVER (ORDER BY timestamp_client) AS ts_prev\r\n  FROM sml_v1\r\n  WHERE id = \"$id\"\r\n    AND timestamp_client BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\r\n),\r\ndeltas AS (\r\n  SELECT\r\n    ts,\r\n    (wh - wh_prev) AS delta_wh\r\n  FROM verbrauch\r\n  WHERE wh_prev IS NOT NULL\r\n    AND (wh - wh_prev) >= 0\r\n),\r\ngesamt_kwh AS (\r\n  SELECT SUM(delta_wh) / 1000 AS total_kwh FROM deltas\r\n),\r\nco2_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    c.value\r\n  ) AS co2_gramm\r\n  FROM deltas d\r\n  JOIN co2_intensity_hourly c\r\n    ON c.zone = 'DE_LU'\r\n    AND c.emission_type = 'Operational'\r\n    AND c.forecast_type = 'Actual'\r\n    AND c.ts_utc = DATE_FORMAT(FROM_UNIXTIME(d.ts), '%Y-%m-%d %H:00:00')\r\n),\r\npreis_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    (p.price_eur_mwh / 1000)\r\n  ) AS kosten_eur\r\n  FROM deltas d\r\n  JOIN power_prices p\r\n    ON p.bidding_zone = 'DE-LU'\r\n    AND p.unix_timestamp = (\r\n      FLOOR(d.ts / 900) * 900\r\n    )\r\n)\r\nSELECT\r\n\r\n  co2_weighted.co2_gramm                                      AS \"CO2 gesamt (g)\"\r\nFROM gesamt_kwh, co2_weighted, preis_weighted;"
    }
   ]
  },
  {
   "title": "CO2 pro kWh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "g/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hz-v1",
     "rawSql": "WITH verbrauch AS (\r\n  SELECT\r\n    timestamp_client AS ts,\r\n    meter_value / 10 AS wh,\r\n    LAG(meter_value / 10) OVER (ORDER BY timestamp_client) AS wh_prev,\r\n    LAG(timestamp_client)  OVER (ORDER BY timestamp_client) AS ts_prev\r\n  FROM sml_v1\r\n  WHERE id = \"$id\"\r\n    AND timestamp_client BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\r\n),\r\ndeltas AS (\r\n  SELECT\r\n    ts,\r\n    (wh - wh_prev) AS delta_wh\r\n  FROM verbrauch\r\n  WHERE wh_prev IS NOT NULL\r\n    AND (wh - wh_prev) >= 0\r\n),\r\ngesamt_kwh AS (\r\n  SELECT SUM(delta_wh) / 1000 AS total_kwh FROM deltas\r\n),\r\nco2_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    c.value\r\n  ) AS co2_gramm\r\n  FROM deltas d\r\n  JOIN co2_intensity_hourly c\r\n    ON c.zone = 'DE_LU'\r\n    AND c.emission_type = 'Operational'\r\n    AND c.forecast_type = 'Actual'\r\n    AND c.ts_utc = DATE_FORMAT(FROM_UNIXTIME(d.ts), '%Y-%m-%d %H:00:00')\r\n),\r\npreis_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    (p.price_eur_mwh / 1000)\r\n  ) AS kosten_eur\r\n  FROM deltas d\r\n  JOIN power_prices p\r\n    ON p.bidding_zone = 'DE-LU'\r\n    AND p.unix_timestamp = (\r\n      FLOOR(d.ts / 900) * 900\r\n    )\r\n)\r\nSELECT\r\n  co2_weighted.co2_gramm / gesamt_kwh.total_kwh              AS \"CO2 pro kWh (g/kWh)\"\r\nFROM gesamt_kwh, co2_weighted, preis_weighted;"
    }
   ]
  },
  {
   "title": "Kosten gesamt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hz-v1",
     "rawSql": "WITH verbrauch AS (\r\n  SELECT\r\n    timestamp_client AS ts,\r\n    meter_value / 10 AS wh,\r\n    LAG(meter_value / 10) OVER (ORDER BY timestamp_client) AS wh_prev,\r\n    LAG(timestamp_client)  OVER (ORDER BY timestamp_client) AS ts_prev\r\n  FROM sml_v1\r\n  WHERE id = \"$id\"\r\n    AND timestamp_client BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\r\n),\r\ndeltas AS (\r\n  SELECT\r\n    ts,\r\n    (wh - wh_prev) AS delta_wh\r\n  FROM verbrauch\r\n  WHERE wh_prev IS NOT NULL\r\n    AND (wh - wh_prev) >= 0\r\n),\r\ngesamt_kwh AS (\r\n  SELECT SUM(delta_wh) / 1000 AS total_kwh FROM deltas\r\n),\r\nco2_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    c.value\r\n  ) AS co2_gramm\r\n  FROM deltas d\r\n  JOIN co2_intensity_hourly c\r\n    ON c.zone = 'DE_LU'\r\n    AND c.emission_type = 'Operational'\r\n    AND c.forecast_type = 'Actual'\r\n    AND c.ts_utc = DATE_FORMAT(FROM_UNIXTIME(d.ts), '%Y-%m-%d %H:00:00')\r\n),\r\npreis_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    (p.price_eur_mwh / 1000)\r\n  ) AS kosten_eur\r\n  FROM deltas d\r\n  JOIN power_prices p\r\n    ON p.bidding_zone = 'DE-LU'\r\n    AND p.unix_timestamp = (\r\n      FLOOR(d.ts / 900) * 900\r\n    )\r\n)\r\nSELECT\r\n  preis_weighted.kosten_eur                                   AS \"Kosten gesamt (€)\"\r\nFROM gesamt_kwh, co2_weighted, preis_weighted;"
    }
   ]
  },
  {
   "title": "Kosten pro kWh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ct/kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "hz-v1",
     "rawSql": "WITH verbrauch AS (\r\n  SELECT\r\n    timestamp_client AS ts,\r\n    meter_value / 10 AS wh,\r\n    LAG(meter_value / 10) OVER (ORDER BY timestamp_client) AS wh_prev,\r\n    LAG(timestamp_client)  OVER (ORDER BY timestamp_client) AS ts_prev\r\n  FROM sml_v1\r\n  WHERE id = \"$id\"\r\n    AND timestamp_client BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\r\n),\r\ndeltas AS (\r\n  SELECT\r\n    ts,\r\n    (wh - wh_prev) AS delta_wh\r\n  FROM verbrauch\r\n  WHERE wh_prev IS NOT NULL\r\n    AND (wh - wh_prev) >= 0\r\n),\r\ngesamt_kwh AS (\r\n  SELECT SUM(delta_wh) / 1000 AS total_kwh FROM deltas\r\n),\r\nco2_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    c.value\r\n  ) AS co2_gramm\r\n  FROM deltas d\r\n  JOIN co2_intensity_hourly c\r\n    ON c.zone = 'DE_LU'\r\n    AND c.emission_type = 'Operational'\r\n    AND c.forecast_type = 'Actual'\r\n    AND c.ts_utc = DATE_FORMAT(FROM_UNIXTIME(d.ts), '%Y-%m-%d %H:00:00')\r\n),\r\npreis_weighted AS (\r\n  SELECT SUM(\r\n    d.delta_wh / 1000 *\r\n    (p.price_eur_mwh / 1000)\r\n  ) AS kosten_eur\r\n  FROM deltas d\r\n  JOIN power_prices p\r\n    ON p.bidding_zone = 'DE-LU'\r\n    AND p.unix_timestamp = (\r\n      FLOOR(d.ts / 900) * 900\r\n    )\r\n)\r\nSELECT\r\n  preis_weighted.kosten_eur / gesamt_kwh.total_kwh * 100     AS \"Preis pro kWh (ct/kWh)\"\r\nFROM gesamt_kwh, co2_weighted, preis_weighted;"
    }
   ]
  },
  {
   "title": "Leistung (logarithmisch)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp_client as 'time', \n  (meter_value - LAG(meter_value) OVER (PARTITION BY id ORDER BY timestamp_client)) *360 / NULLIF(timestamp_client - LAG(timestamp_client) \n  OVER (PARTITION BY id ORDER BY timestamp_client), 0) AS \"Leistung\" \nFROM sml_v1 \nWHERE\n  id = \"$id\"  \n  AND\n  $__unixEpochFilter(timestamp_client)\nORDER BY from_unixtime(timestamp_client)\n"
    }
   ]
  }
 ]
}